name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby:
          - '3.0.2'
          - head

    steps:
      - uses: actions/checkout@v2
      - name: Install libcapstone Linux
        if: matrix.os == 'ubuntu'
        run: |
            sudo apt-get update -y
            sudo apt-get install -y libcapstone-dev

      - name: Install libcapstone macOS
        if: matrix.os == 'macos'
        run: |
            brew update
            brew install capstone

      - name: Set up Ruby
        uses: tenderlove/setup-ruby@0a3bd51d9e8e1b30bc129bbb6934f68bdb648f45
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake clobber compile test
